[build]
  command = "yarn build"
  functions = "lambda"
  publish = ".next"

[dev]
  autoLaunch = false

[[redirects]]
  from = "/blog/2020/05/switching-to-gatsby"
  to = "/blog/post/2020/05/switching-to-gatsby"
  status = 301

[[redirects]]
  from = "/blog/2020/01/experimenting-with-protobufs-generated-types-in-rust"
  to = "/blog/post/2020/01/experimenting-with-protobufs-generated-types-in-rust"
  status = 301

[[redirects]]
  from = "/blog/2019/09/migrated-to-hugo"
  to = "/blog/post/2019/09/migrated-to-hugo"
  status = 301

[[redirects]]
  from = "/blog/2016/08/relative-line-numbers-and-you"
  to = "/blog/post/2016/08/relative-line-numbers-and-you"
  status = 301

[[redirects]]
  from = "/blog/2016/01/vim-splitting-shortcuts"
  to = "/blog/post/2016/01/vim-splitting-shortcuts"
  status = 301

[[redirects]]
  from = "/blog/2015/03/long-python-commands-down-to-size"
  to = "/blog/post/2015/03/long-python-commands-down-to-size"
  status = 301

[[redirects]]
  from = "/blog/2014/10/whats-the-deal-with-the-name-hockeybuggy"
  to = "/blog/post/2014/10/whats-the-deal-with-the-name-hockeybuggy"
  status = 301

[[redirects]]
  from = "/blog/2014/09/state-of-the-dotfiles"
  to = "/blog/post/2014/09/state-of-the-dotfiles"
  status = 301

[[redirects]]
  from = "/blog/2014/06/adding-semantics"
  to = "/blog/post/2014/06/adding-semantics"
  status = 301

[[redirects]]
  from = "/blog/2013/09/migrated-to-jekyll"
  to = "/blog/post/2013/09/migrated-to-jekyll"
  status = 301

[[redirects]]
  from = "/blog/2013/03/moving-beymond-word-wise-motions"
  to = "/blog/post/2013/03/moving-beymond-word-wise-motions"
  status = 301

[[redirects]]
  from = "/blog/2013/01/adding-sass-files"
  to = "/blog/post/2013/01/adding-sass-files"
  status = 301

[[redirects]]
  from = "/blog/2012/12/taking-this-pelican-site-live"
  to = "/blog/post/2012/12/taking-this-pelican-site-live"
  status = 301
