# Based on https://www.specialcase.dev/blog/sharing-steps-in-github-action-workflows/

name: "Shared steps to build the site"
description: "Used to share steps between jobs that build the static site."
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/rust-setup

    - name: Cache site build output
      id: cache-site-build
      uses: actions/cache@v5
      with:
        path: |
          ${{ github.workspace }}/dist
        key: ${{ github.run_id }}

    - name: Build
      if: ${{ steps.cache-site-build.outputs.cache-hit != 'true' }}
      env:
        CI: "true"
      shell: bash
      run: cargo run --release --manifest-path ssg/Cargo.toml
