# Based on https://www.specialcase.dev/blog/sharing-steps-in-github-action-workflows/

name: "Shared steups to build the site"
description: "Used to share steps between jobs that build the static site."
runs:
  using: "composite"
  steps:
    - name: Cache next build cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-cache-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-cache-${{ hashFiles('**/yarn.lock') }}-

    - name: Cache next build
      id: cache-next-build
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/public
          ${{ github.workspace }}/.next/
        key: ${{ github.run_id }}

    - name: Build
      if: ${{ steps.cache-next-build.outputs.cache-hit != 'true' }}
      env:
        CI: "true"
      shell: bash
      run: |
        yarn run build
