# Based on https://www.specialcase.dev/blog/sharing-steps-in-github-action-workflows/

name: "Shared steups to build the site"
description: "Used to share steps between jobs that build the static site."
runs:
  using: "composite"
  steps:
    # Based on: https://nextjs.org/docs/advanced-features/ci-build-caching#github-actions
    - name: Cache next build
      id: cache-next-build
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/public
          ${{ github.workspace }}/.next/
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

    - name: Build
      if: ${{ steps.cache-next-build.outputs.cache-hit != 'true' }}
      env:
        CI: "true"
      shell: bash
      run: |
        yarn run build
