# Based on https://www.specialcase.dev/blog/sharing-steps-in-github-action-workflows/

name: "Shared Steps"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16.19.1
        cache: 'yarn'

    - name: Install
      run: |
        yarn install
