# Based on https://www.specialcase.dev/blog/sharing-steps-in-github-action-workflows/

name: "Shared setup steps"
description: "Used to share steps between jobs that install node dependancies for the project."
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 20.16.0
        cache: 'yarn'

    - name: Install npm packages
      shell: bash
      run: yarn
