name: end to end tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.15.1

    - name: Install dependancies
      run: |
        yarn install

    - name: Run Tests
      env:
        CI: true
        NODE_ENV: "prod"  # "test" was casusing SSR to fail.
      run: |
        yarn run test:e2e --verbose

    - uses: actions/upload-artifact@v2
      with:
        name: e2e_test_screenshots
        path: e2e_tests/screenshots
