name: tests

on: [push]

jobs:
  rust-checks:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v5
    - uses: ./.github/actions/rust-setup
      with:
        components: rustfmt, clippy
    - name: cargo fmt
      run: cargo fmt --manifest-path ssg/Cargo.toml --check
    - name: cargo clippy
      run: cargo clippy --manifest-path ssg/Cargo.toml --all-targets -- -D warnings
    - name: cargo test
      run: cargo test --manifest-path ssg/Cargo.toml


  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v5
    - uses: ./.github/actions/build-site


  run-end-to-end-tests:
    needs: build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v5
    - uses: ./.github/actions/shared-setup
    - uses: ./.github/actions/build-site
    - name: Install Playwright browsers
      run: yarn playwright install --with-deps chromium
    - name: Run Tests
      env:
        CI: true
      run: |
        yarn run test:e2e
    - uses: actions/upload-artifact@v5
      if: always()
      with:
        name: playwright-report
        path: |
          playwright-report/
          e2e_tests/screenshots/
